export enum OrderStatus {
  WAITING_FOR_PICKUP_DRIVER = 'WAITING_FOR_PICKUP_DRIVER',
  LAUNDRY_EN_ROUTE_TO_OUTLET = 'LAUNDRY_EN_ROUTE_TO_OUTLET',
  LAUNDRY_ARRIVED_AT_OUTLET = 'LAUNDRY_ARRIVED_AT_OUTLET',
  LAUNDRY_BEING_WASHED = 'LAUNDRY_BEING_WASHED',
  LAUNDRY_BEING_IRONED = 'LAUNDRY_BEING_IRONED',
  LAUNDRY_BEING_PACKED = 'LAUNDRY_BEING_PACKED',
  WAITING_FOR_PAYMENT = 'WAITING_FOR_PAYMENT',
  LAUNDRY_READY_FOR_DELIVERY = 'LAUNDRY_READY_FOR_DELIVERY',
  LAUNDRY_OUT_FOR_DELIVERY = 'LAUNDRY_OUT_FOR_DELIVERY',
  LAUNDRY_DELIVERED_TO_CUSTOMER = 'LAUNDRY_DELIVERED_TO_CUSTOMER',
  COMPLETED = 'COMPLETED',
}

export enum PaymentStatus {
  UNPAID = 'UNPAID',
  PAID = 'PAID',
  FAILED = 'FAILED',
  PENDING = 'PENDING',
  EXPIRED = 'EXPIRED',
}

export enum ComplaintStatus {
  OPEN = 'OPEN',
  IN_REVIEW = 'IN_REVIEW',
  RESOLVED = 'RESOLVED',
}

